export interface AuthUser {
    id: string,
    avatar: string,
    firstName: string,
    lastName: string,
    dateOfBirth: string,
    gender: string,
    phoneNumber: string,
    email: string,
    address: string,
    yearExperience: string,
    summary: string,
    position: string,
    major: string,
    link: string,
    status: string,
    role: string,
    company: any,
    cv: string,
}
